name: home
version: 0.0.1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  groups:
    path: ../groups
  core:
    path: ../../core
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  navigation:
    path: ../../navigation

  # Features
  dashboard:
    path: ../dashboard
  tacks:
    path: ../tacks

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
