name: core
version: 0.0.1
publish_to: none
description: Core package

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  get_it: ^7.2.0
  device_info_plus: ^4.1.2
  equatable: ^2.0.3
  firebase_core: ^1.20.1
  firebase_dynamic_links: ^4.3.4
  firebase_messaging: ^13.0.1
  flutter_bloc: ^7.3.3
  flutter_local_notifications: ^9.9.1
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  connectivity: ^3.0.3
  flutter_i18n: ^0.32.4
  path_provider: ^2.0.11
  rxdart: ^0.27.5
  shared_preferences: ^2.0.13
  share_plus: ^4.0.10
  url_launcher: ^6.1.5
  flutter_multi_formatter: ^2.5.1

  #Payment
  flutter_stripe: ^4.0.0
  plaid_flutter: ^2.2.2

  data:
    path: ../data
  domain:
    path: ../domain
  core_ui:
    path: ../core_ui
  navigation:
    path: ../navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
