name: core
version: 0.0.1
publish_to: none
description: Core package

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  navigation:
    path: ../navigation

  connectivity: ^3.0.3
  equatable: ^2.0.3
  flutter_bloc: ^7.3.3
  flutter_i18n: ^0.32.4
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.13
  share_plus: ^4.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
