name: splash
version: 0.0.1
publish_to: none
description: Module with app splash screen

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  auth:
    path: ../auth
  core:
    path: ../../core
  core_ui:
    path: ../../core_ui
  navigation:
    path: ../../navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
