name: core_ui
version: 0.0.1
publish_to: none
description: Core UI package

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  animated_toggle_switch: ^0.5.2
  expandable_text: ^2.3.0
  grouped_list: ^5.1.2
  flutter_html: ^3.0.0-alpha.5
  flutter_keyboard_visibility: ^5.3.0
  flutter_svg: ^1.1.1+1
  pin_code_fields: ^7.4.0

  core:
    path: ../core
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  # Components
  app_dialog:
    path: ../components/app_dialog
  image_cropper:
    path: ../components/image_cropper
  segment_controller:
    path: ../components/segment_controller

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/navigation/
    - assets/svg/
